# Méthodes Numériques - TP noté ET4

## Consignes
A la fin du TP, on vous demande d'envoyer un jupyter Notebook NOM_Prénom_Exp.ipynb à votre chargé de TP (Joel.gay@universite-paris-saclay.fr ou anne-catherine.letournel@universite-paris-saclay.fr). Le sujet de l'email devra être [TP Noté ET4 MethNum] NOM prénom

In [24]:
import numpy as np
from numpy import linalg as la
from scipy import linalg as sla
import matplotlib.pyplot as plt

## Introduction

Soit donnés le système d’équations différentielles du premier ordre :

$$
\left\{\begin{array}{rcl}
\frac{d}{dt}x_1(t) & = & a_{11}x_1(t) + a_{12}x_2(t) + a_{13}x_3(t), \\
\frac{d}{dt}x_2(t) & = & a_{21}x_1(t) + a_{22}x_2(t) + a_{23}x_3(t), \\
\frac{d}{dt}x_3(t) & = & a_{31}x_1(t) + a_{32}x_2(t) + a_{33}x_3(t), \\
\end{array}\right.
$$

et sa condition initiale $𝑥_1(0)$, $𝑥_2(0)$ et $𝑥_3(0)$, où les $a_{ij}$ sont des coefficients réels. La solution d’un tel problème nous donne des informations sur la dépendance en temps de $x_1$, $x_2$ et $x_3$. Le problème peut être écrit avec une notation matricielle :

$$
\left\{\begin{array}{rcl}
\frac{d}{dt}\vec{x}(t) & = & A \vec{x}(t)\\
\vec{x}(0) & = & \begin{pmatrix}x_1(0)\\x_2(0)\\x_3(0)\end{pmatrix}\\
\end{array}\right. \qquad \text{ où } \vec{x}(t) = \begin{pmatrix}x_1(t)\\x_2(t)\\x_3(t)\end{pmatrix} \quad\text{  et  }\quad A = \begin{pmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{pmatrix}
$$

La solution formelle du problème est : 
$$\vec{x}(t) = e^{At}\vec{x}(0)$$

où $e^{At}$ est une matrice appelée <b>exponentielle de la matrice $At$</b>, et définie avec la série de Taylor :
$$e^{At} = \sum_{k=0}^{\infty} \frac{t^k}{k!}A^k = I + tA + \frac{t^2}{2}A^2 + \frac{t^3}{6}A^3 + \dots+ \frac{t^k}{k!}A^k + \dots $$
<i>Remarque : Ici on utilise la notation standard $A^k$ pour indiquer la multiplication matricielle de $A$, $k$ fois ; par exemple : $A^2 = A\cdot A$ et $A^3 = A \cdot A \cdot A$.</i>

Une évaluation efficace de la matrice $e^{At}$ consiste à résoudre le problème
sans utiliser des algorithmes pour l’intégration numérique des équations
différentielles: pour obtenir le valeurs de $x_1(t)$, $x_2(t)$ et $x_3(t)$ au temps $t$, il faut
simplement appliquer la matrice $e^{At}$ au vecteur $\vec{x}(0)$ qui représente la con-
dition initiale. Le but de ce TP est d’apprendre à évaluer l’exponentielle d’une matrice à l'aide de python et de la série de Taylor.

<b> Attention: l’exponentielle de la matrice $At$ n’est pas la matrice composée des exponentielles des éléments de $At$ : </b>
$$ 
e^{At} \ne \begin{pmatrix}e^{a_{11}t}&e^{a_{12}t}&e^{a_{13}t}\\e^{a_{21}t}&e^{a_{22}t}&e^{a_{23}t}\\e^{a_{31}t}&e^{a_{32}t}&e^{a_{33}t}\end{pmatrix}
$$

## Série de Taylor

1) Écrire une fonction somme partielle de rang <tt>nmax</tt>: <tt> SomPart(A,t,nmax)</tt> dont les paramètres sont une matrice <tt>A</tt>, un temps <tt>t</tt> et un nombre entier positif <tt>nmax</tt>. Cette fonction retourne la matrice ExpAt, qui est l’exponentielle de la matrice $A$ multipliée par $t$ en utilisant la définition de la série de Taylor en calculant les $nmax$ premiers termes de la série, ainsi que le dernier terme de la série $\frac{t^{nmax}}{nmax!}A^{nmax}$.<br>
On pourra utiliser les fonctions python <tt>np.math.factorial()</tt> et <tt>la.matrix_power()</tt> (mais ce n'est pas indispensable). Notez bien que la puissance $k$ d'une matrice $A$ n'est pas <tt>A**k</tt>. 

In [134]:
def Som_part(A,t,nmax):
    res = np.zeros((len(A),len(A)))
    for i in range (len(A)):
        res[i][i] = 1
    for k in range(1,nmax):
        res = (t**k) / (np.math.factorial(k))* (la.matrix_power(A,k)) + res
        
    return res
    

2) Tester votre fonction sur $A = \begin{pmatrix} -6 & -2 & 2 \\ 0 & -2 & -4 \\ 3 & 1 & -1 \end{pmatrix}$ pour les temps $t = 0.1$ et $t = 3$ et en comparant les résultats obtenus avec la fonction Python <tt>sla.expm()</tt>.<br>
**NB :** prendre $nmax$ suffisamment grand dans chaque cas pour constater que le dernier terme de la série, qui est une matrice, tend vers la matrice nulle. Si cela semble diverger, aller plus loin. 

In [135]:
A = np.array([[-6,-2,2],[0,-2,-4],[3,1,-1]])
B = Som_part(A,0.1,100)
print(B)
C = Som_part(A,3,500)
print(C)
sla.expm(0.1*A)


[[ 0.571 -0.128  0.173]
 [-0.045  0.805 -0.346]
 [ 0.214  0.064  0.914]]
[[ 1.199e+06  5.994e+05  6.666e-01]
 [-5.994e+05 -7.971e+05 -1.333e+00]
 [-5.994e+05 -7.971e+05  6.667e-01]]


array([[ 0.571, -0.128,  0.173],
       [-0.045,  0.805, -0.346],
       [ 0.214,  0.064,  0.914]])

Pour des questions de complexité, on souhaite pouvoir arrêter le calcul de la somme partielle quand la matrice dernier terme est suffisamment petite. <br>
Soit $r$ la plus grande valeur propre de la matrice $At$ en module. Cette valeur s'appelle le rayon spectral de $At$. On admettra que l'écart entre la valeur exacte $e^{At}$ et la somme partielle de rang $n$ est proportionnel à l'expression $e^r \cdot \frac{r^{n+1}}{(n+1)!}$ et qu'une condition d'arrêt acceptable est de majorer cette quantité par une tolérance <tt>tol</tt>.

3) Quel algorithme du cours permettrait de récupérer $r$ ? 

C'est l'algorithme de la méthode de la puissance

Programmez la fonction python permettant de calculer r avec cet algorithme du cours.

In [137]:
def Python(L,N,tol,itermax):
    k=0
    while(k<itermax):
        XK=L.dot(N)/la.norm(L.dot(N))
        Lambda=XK.transpose()@L@XK
        k+=1
        
        if (la.norm(L.dot(XK)-Lambda*XK)<tol):
            break
        N=XK
    return Lambda


Vérifier la valeur de $r$ trouvée ci-dessus en utilisant la fonction python appropriée qui retourne toutes les valeurs propres d'une matrice et prenant celle de module maximal. <br>

In [149]:
A = np.array([[-6,-2,2],[0,-2,-4],[3,1,-1]])
t= 0.1
tol = 0.00001
itermax = 1000
r = Python(A*t,np.array([1,2,3]),tol,itermax)
r1 = la.eigvals(A*t)
print(r1)
print(r)


[-6.000e-01 -1.162e-16 -3.000e-01]
-0.6000102998397701


On cherche donc une valeur $n_0$ à partir de laquelle la quantité décrite précédemment est majorée par une tolérance <tt>tol</tt>. 

4) Programmer une fonction python <tt>Iter(A,t,tol)</tt> qui retourne une valeur acceptable de $n_0$ pour le calcul de la somme partielle et la tolérance <tt>tol</tt>.

In [155]:
def Iter(A,t,tol):
    L = A*t
    N = np.zeros(len(A))
    for i in range (len(A)):
        N[i] = i
    k=0
    while(1):
        XK=L.dot(N)/la.norm(L.dot(N))
        Lambda=XK.transpose()@L@XK
        k+=1
        if (la.norm(L.dot(XK)-Lambda*XK)<tol):
            return k
        N=XK

7

5) Assembler les fonctions élémentaires <tt>SomPart</tt> et <tt>Iter</tt> pour écrire une fonction python <tt>ExpAt(A,t,tol)</tt> qui retourne une matrice qui est une bonne approximation de $e^{At}$, ainsi que le nombre de termes de la somme.

In [156]:
def Som_part(A,t,nmax):
    res = np.zeros((len(A),len(A)))
    for i in range (len(A)):
        res[i][i] = 1
    for k in range(1,nmax):
        res = (t**k) / (np.math.factorial(k))* (la.matrix_power(A,k)) + res
        
    return res

def ExpAt(A,t,tol):
    return Som_part(A,t,Iter(A,t,tol))
    
    
    

6) Tester votre fonction à nouveau sur la matrice $A$ précédente, pour $t = 0.1$ et $t = 3$, une tolérance pertinente, et comparer avec la fonction Python <tt>sla.expm()</tt>.

In [162]:
A = np.array([[-6,-2,2],[0,-2,-4],[3,1,-1]])
t = 0.1
tol = 0.0001
print(ExpAt(A,t,tol))
t1 = 3
tol1 = 0.0001
print(ExpAt(A,t1,tol1))

sla.expm(t*A)

[[ 0.571 -0.128  0.173]
 [-0.045  0.805 -0.346]
 [ 0.214  0.064  0.914]]
[[ 4.039e+06  2.020e+06 -4.415e+00]
 [-2.020e+06 -1.010e+06  8.829e+00]
 [-2.020e+06 -1.010e+06  3.207e+00]]


array([[ 0.571, -0.128,  0.173],
       [-0.045,  0.805, -0.346],
       [ 0.214,  0.064,  0.914]])

## Résolution du problème

7) Utiliser la fonction <tt>ExpAt</tt> et le résultat de l’équation pour résoudre le système différentiel initial dans le cas où $A = \begin{pmatrix} -6 & -2 & 2 \\ 0 & -2 & -4 \\ 3 & 1 & -1 \end{pmatrix}$, et la condition initiale est spécifiée par les valeurs $x_1(0) = 1$, $x_2(0) = 2$ et $x_3(0) = 2$. Faire un graphe des trois courbes $x_1 (t)$, $x_2(t)$ et $x_3(t)$ pour $t \in [0, 3]$ en utilisant $100$ valeurs discrètes du temps. <br>
Attention: la lisibilité du graphe va être prise en compte au moment de l’évaluation du TP. 

In [164]:
A = np.array([[-6,-2,2],[0,-2,-4],[3,1,-1]])
x0 = np.array([1,2,2])
tol = 0.0001
t = np.linspace(0,3,2)
ExpAt1 = ExpAt(A,t,tol)
plt.plot()

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

## Valeurs propres - partie 1

<i>La ligne ci-dessous diminue la précision affichée pour plus de lisibilité, mais ne vous formalisez pas si cela ne semble pas systématique : c'est lié à des options d'affichages de python complexes à gérer. </i>

%precision 3 

8) Toujours pour la même matrice $A$, calculer les valeurs propres de $A$, $(\lambda_i)$, et de $e^A$, $(\mu_i)$ (si votre fonction </tt>ExpAt</tt> ne marche pas, utiliser la fonction <tt>sla.expm()</tt> pour calculer $e^A$). Montrer que pour chaque valeur propre $\mu_i$ il y a une valeur propre $\lambda_i$ telle que $\mu_i = e^{\lambda_i}$. 

In [169]:
valPropre = la.eigvals(A)
A = np.array([[-6,-2,2],[0,-2,-4],[3,1,-1]])
x0 = np.array([1,2,2])
tol = 0.0001
valPropreEa = la.eigvals(ExpAt(A,t,tol))

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

9) Montrer que les vecteurs propres de $A$ sont vecteurs propres de $e^A$

## Valeurs propres - partie 2

Les deux propriétés qu’on vient de vérifier ne sont pas un cas particulier, et nous suggèrent une nouvelle méthode pour calculer $e^A$. Cette méthode est valable si les valeurs propres de $A$ ne sont pas dégénérées, c’est-à-dire s’il n’y a pas deux valeurs propres identiques.

10) Écrire une fonction : <tt>ExpAt2(A,t)</tt> dont les paramètres sont une matrice $A$ et un temps $t$. Cette fonction retourne la matrice $e^{At}$, qui est l’exponentielle de la matrice $A$ multipliée par $t$, calculée avec cette procédure :

$\qquad$ a) on utilise la fonction <tt>la.eig()</tt> pour calculer les matrices $D$ et $P$ qui apparaissent dans la diagonalisation de la matrice $A$ :
$$A = P D P^{-1}, \qquad \qquad \text{ où } D = \begin{pmatrix} \lambda_1 & 0 & 0 \\ 0 & \lambda_2 & 0 \\ 0 & 0 & \lambda_3 \end{pmatrix} $$
On rappelle que $D$ est alors une matrice diagonale avec les valeurs propres de $A$, et que $P$ est une matrice de vecteurs propres de $A$. 

$\qquad$ b) On calcule la matrice $D'$ suivante : 
$$D' = \begin{pmatrix}e^{\lambda_1}&0&0 \\ 0&e^{\lambda_2}&0 \\ 0&0&e^{\lambda_3}\end{pmatrix}$$

$\qquad$ c) On calcule la matrice $e^{At}$ en utilisant les résultats précédents : 
$$ e^{At} = P D' P^{-1}$$

11) Tester votre fonction sur $A = \begin{pmatrix} -6 & -2 & 2 \\ 0 & -2 & -4 \\ 3 & 1 & -1 \end{pmatrix}$ pour les temps $t = 0.1$ et $t = 3$ et en comparant les résultats obtenus avec la fonction Python <tt>sla.expm()</tt>.

In [21]:
%precision 8

'%.8f'